---
# .mega-linter.yml
APPLY_FIXES: ["YAML", "JSON", "PYTHON"]
PYTHON_BANDIT_FILTER_REGEX_EXCLUDE: test_.*
# SPELL_LYCHEE_FILTER_REGEX_EXCLUDE:
DISABLE:
  - REPOSITORY
  - COPYPASTE
DISABLE_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - SPELL_LYCHEE
