---
# I suspect we do not need this task
- name: Set necessary facts
  ansible.builtin.set_fact:
    ca_branch: production
    ca_server: repository.egi.eu
  when: ca_verification

# This should be separated into an OS-specific include
- name: Add IGTF repository for YUM
  ansible.builtin.yum_repository:
    name: EGI-trustanchors
    description: EGI-trustanchors repo
    baseurl: "{{ repo_url }}/sw/{{ ca_branch }}/cas/{{ ca_version }}/current/"
    enabled: True
    gpgcheck: True
    gpgkey: "{{ repo_url }}/sw/production/cas/1/GPG-KEY-EUGridPMA-RPM-3"
  when: (ansible_os_family | lower) == 'redhat'

- name: Ensure EGI Policy Core is present
  ansible.builtin.package:
    name: ca-policy-egi-core
    state: present

- name: Ensure WLCG CA package is present
  ansible.builtin.package:
    name: ca-policy-lcg
    state: present
  when: ca_verification

- name: Ensure CRL package is present
  ansible.builtin.package:
    name: fetch-crl
    state: present
  when: crl_deploy
