---
- name: Ensure EPEL is present
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Import UMD GPG keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - "{{ repo_url }}/sw/production/umd/UMD-{{ release }}-RPM-PGP-KEY"
    - "{{ repo_url }}/sw/production/umd/UMD-RPM-PGP-KEY"

- name: Ensure release package is present (RedHat)
  ansible.builtin.package:
    name: "{{ release_url[release] }}"
    state: present

- name: Add UMD base candidate repository
  yum_repository:
    name: "UMD-{{ release }}-candidate-base"
    description: "UMD-{{ release }} candidate - base"
    file: "UMD-{{ release }}-candidate"
    baseurl: "{{ repo_url }}/software/umd/{{ release }}/{{ nick }}/x86_64/base"
    protect: True
    enabled: True
    priority: 1
    gpgcheck: False
  when: enable_candidate_repo

- name: Add UMD updates candidate repository
  yum_repository:
    name: "UMD-{{ release }}-candidate-updates"
    description: "UMD-{{ release }} candidate - updates"
    file: "UMD-{{ release }}-candidate"
    baseurl:
      "{{ repo_url }}/software/umd/{{ release }}/{{ nick }}/x86_64/updates"
    protect: True
    enabled: True
    priority: 1
    gpgcheck: False
  when: enable_candidate_repo

- name: Ensure yum-utils is present
  ansible.builtin.package:
    name: yum-utils
    state: present
  when: enable_testing_repo

# these tasks are not idempotent - they should be replaced with some "replace" tasks, in a block
- name: Enable UMD testing repository
  ansible.builtin.command: yum-config-manager --enable UMD-*-testing
  when: enable_testing_repo
