# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN dnf makecache \
  && dnf update -y \
  && dnf install -y python sudo bash \
  && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf \
  && dnf clean all
